backend:
    build: ./dockerBuild
    links:
        - mongodb
    environment:
        "spring.data.mongodb.host": "mongodb"
        "logging.level.org.springframework.web": "DEBUG"
    ports:
        - "8080:8080"
mongodb:
    container_name: mongodb
    image: mongo